In [1]:
#intergers in bracket
import re

def integers_in_brackets(s):
    pattern = re.compile(r'\[\s*([+-]?\d+)\s*\]')
    
    matches = pattern.findall(s)
    
    return [int(match) for match in matches]

print(integers_in_brackets(" afd [asd] [12 ] [a34] [ -43 ]tt [+12]xxx"))

[12, -43, 12]


In [3]:
# File Listing
def file_listing(filename="src/listing.txt"):
    pattern = re.compile(r'\s*(\d+)\s+(\w+)\s+(\d+)\s+(\d+):(\d+)\s+(.+)')

    results = []

    with open(filename, 'r') as file:
        for line in file:
            match = pattern.search(line)
            if match:
                size = int(match.group(1))
                month = match.group(2)
                day = int(match.group(3))
                hour = int(match.group(4))
                minute = int(match.group(5))
                filename = match.group(6)
                
                results.append((size, month, day, hour, minute, filename))
    
    return results

In [5]:
# red green blue 
def red_green_blue():
    filepath = 'src/rgb.txt'
    
    cleaned_lines = []

    pattern = re.compile(r'\s*(\d+)\s+(\d+)\s+(\d+)\s+(.+?)\s*$')

    with open(filepath, 'r') as file:
        next(file)
        
        for line in file:
            match = pattern.match(line)
            if match:
                red, green, blue, colorname = match.groups()
                cleaned_line = f"{red}\t{green}\t{blue}\t{colorname}"
                cleaned_lines.append(cleaned_line)

    return cleaned_lines

#cleaned_list = red_green_blue()
#for line in cleaned_list[:5]:  
#    print(line)

In [6]:
# word frequencies
def word_frequencies(filename):
    word_count = {}

    strip_chars = """!"#$%&'()*,-./:;?@[]_"""

    with open(filename, 'r') as file:
        for line in file:
            words = line.split()
            for word in words:
                cleaned_word = word.strip(strip_chars)
                cleaned_word = cleaned_word.lower()
                if cleaned_word:
                    if cleaned_word in word_count:
                        word_count[cleaned_word] += 1
                    else:
                        word_count[cleaned_word] = 1

    return word_count

#frequencies = word_frequencies('src/yourfile.txt')
#for word, count in frequencies.items():
#    print(f"{word}\t{count}")

In [13]:
#Prepend Class
class Prepend:
    def __init__(self, start):
        self.start = start

    def write(self, s):
        print(self.start + s)

# Example usage
p = Prepend("+++ ")
p.write("Hello")

+++ Hello


In [14]:
s = Prepend("Mr.")
s.write(" Smith")

Mr. Smith


In [17]:
# rational class 
from math import gcd

class Rational:
    def __init__(self, numerator, denominator):
        if denominator == 0:
            raise ValueError("Denominator cannot be zero")
        self.numerator = numerator
        self.denominator = denominator
        self._normalize()

    def _normalize(self):
        common_divisor = gcd(self.numerator, self.denominator)
        self.numerator //= common_divisor
        self.denominator //= common_divisor
        if self.denominator < 0:
            self.numerator = -self.numerator
            self.denominator = -self.denominator

    def __str__(self):
        return f"{self.numerator}/{self.denominator}"

    def __add__(self, other):
        numerator = self.numerator * other.denominator + other.numerator * self.denominator
        denominator = self.denominator * other.denominator
        return Rational(numerator, denominator)

    def __sub__(self, other):
        numerator = self.numerator * other.denominator - other.numerator * self.denominator
        denominator = self.denominator * other.denominator
        return Rational(numerator, denominator)

    def __mul__(self, other):
        numerator = self.numerator * other.numerator
        denominator = self.denominator * other.denominator
        return Rational(numerator, denominator)

    def __truediv__(self, other):
        if other.numerator == 0:
            raise ZeroDivisionError("Cannot divide by zero")
        numerator = self.numerator * other.denominator
        denominator = self.denominator * other.numerator
        return Rational(numerator, denominator)

    def __eq__(self, other):
        return (self.numerator == other.numerator) and (self.denominator == other.denominator)

    def __lt__(self, other):
        return self.numerator * other.denominator < other.numerator * self.denominator

    def __le__(self, other):
        return self.numerator * other.denominator <= other.numerator * self.denominator

    def __gt__(self, other):
        return self.numerator * other.denominator > other.numerator * self.denominator

    def __ge__(self, other):
        return self.numerator * other.denominator >= other.numerator * self.denominator

r1 = Rational(1, 4)
r2 = Rational(1, 2)

print(r1)  # Expected Output: 1/4
print(r2)  # Expected Output: 1/2

print(r1 + r2)  # Expected Output: 3/4
print(r1 - r2)  # Expected Output: -1/4
print(r1 * r2)  # Expected Output: 1/8
print(r1 / r2)  # Expected Output: 1/2

print(r1 == r2)  # Expected Output: False
print(r1 < r2)   # Expected Output: True
print(r1 > r2)   # Expected Output: False

1/4
1/2
3/4
-1/4
1/8
1/2
False
True
False


In [19]:
#error excpetion handling
def extract_numbers(s):
    words = s.split()
    numbers = []
    
    for word in words:
        try:
            number = int(word)
        except ValueError:
            try:
                number = float(word)
            except ValueError:
                continue
        numbers.append(number)
    
    return numbers
print(extract_numbers("abd 123 1.2 test 13.2 -1"))

[123, 1.2, 13.2, -1]


In [53]:
# rows and Columns 
import numpy as np
a = np.random.randint(0, 10, (4,4))

In [61]:
print(a)

[[2 3 0 6]
 [9 1 0 7]
 [0 3 4 7]
 [2 3 0 8]]


In [62]:
print(a.T)

[[2 9 0 2]
 [3 1 3 3]
 [0 0 4 0]
 [6 7 7 8]]


In [64]:
t_arr = a.T
print(t_arr)


[[2 9 0 2]
 [3 1 3 3]
 [0 0 4 0]
 [6 7 7 8]]


In [78]:
def get_rows(arr):
    return [arr[i] for i in range(arr.shape[0])]
rows = get_rows(a)
for row in rows:
    print(row)

[2 3 0 6]
[9 1 0 7]
[0 3 4 7]
[2 3 0 8]


In [68]:
def get_col(arr):
    return [arr[:, j] for j in range(arr.shape[1])]
cols = get_col(a)
for col in cols:
    print(col)

[2 9 0 2]
[3 1 3 3]
[0 0 4 0]
[6 7 7 8]


In [79]:
a.shape[0]

4

In [93]:
arr = a.reshape(4,4)
print(arr)

[[2 3 0 6]
 [9 1 0 7]
 [0 3 4 7]
 [2 3 0 8]]


In [94]:
def get_row_vectors(array):
    return [row.reshape(1, -1) for row in array]

def get_column_vectors(array):
    return [array[:, j].reshape(-1, 1) for j in range(array.shape[1])]
a = np.array([[5, 0, 3],
              [3, 7, 9]])

row_vectors = get_row_vectors(a)
print("Row vectors:")
for vec in row_vectors:
    print(vec)

column_vectors = get_column_vectors(a)
print("\nColumn vectors:")
for vec in column_vectors:
    print(vec)

Row vectors:
[[5 0 3]]
[[3 7 9]]

Column vectors:
[[5]
 [3]]
[[0]
 [7]]
[[3]
 [9]]


In [153]:
def diamond(n):
    size = 2 * n - 1
    # Initialize a zero matrix of the correct size
    mat = np.zeros((size, size), dtype=int)
    
    # Create the diagonal pattern
    upper_diag = np.eye(size, k=n-1, dtype=int)
    lower_diag = np.eye(size, k=-(n-1), dtype=int)
    
    # Combine diagonals to form the diamond shape
    mat = upper_diag + lower_diag + upper_diag[::-1] + lower_diag[::-1]
    mat[mat != 0] = 1
    return mat

print(diamond(5))
print(diamond(1))


[[0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 1 0 0]
 [0 0 0 1 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0]]
[[1]]


In [160]:
def vector_lengths(arr):
    squared_sums = np.sum(arr**2, axis=1)
    lengths = np.sqrt(squared_sums)
    return lengths

arr = np.array([[3, 4], [1, 2], [6, 8], [4,5], [2,3]])
print(vector_lengths(arr))

[ 5.          2.23606798 10.          6.40312424  3.60555128]


In [161]:
def vector_angles(X, Y):
    dot_product = np.sum(X * Y, axis=1)
    
    norms_X = np.sqrt(np.sum(X**2, axis=1))
    norms_Y = np.sqrt(np.sum(Y**2, axis=1))
    
    cos_theta = dot_product / (norms_X * norms_Y)
    
    cos_theta = np.clip(cos_theta, -1.0, 1.0)
    
    angles_radians = np.arccos(cos_theta)
    angles_degrees = np.degrees(angles_radians)
    
    return angles_degrees

X = np.array([[1, 0], [0, 1], [1, 1]])
Y = np.array([[1, 1], [1, 0], [0, 1]])
print(vector_angles(X, Y))

[45. 90. 45.]


In [190]:
#multiplication table
def no_loop_table(n): 
    a = np.arange(n)
    b = np.arange(n).reshape((n,1))
    c= a*b
    print(c)
no_loop_table(10)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]
